openapi: 3.0.0
info:
  title: Example API
  description: REST API документація для вашого Node.js + Express проєкту
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /health:
    get:
      summary: Health check
      description: Перевіряє, чи працює сервер
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /auth/register:
    post:
      summary: Реєстрація користувача
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: username
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: secret123
      responses:
        '201':
          description: User created
        '400':
          description: Validation error

  /auth/login:
    post:
      summary: Логін користувача
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: secret123
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
