version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_NAME=${DB_NAME:-yummi}
      - DB_USER=${DB_USER:-pg_user}
      - DB_PASS=${DB_PASS:-pg_password}
      - DB_PORT=${DB_PORT:-5432}
      - PORT=${PORT:-3000}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/api/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-pg_user}
      - POSTGRES_PASSWORD=${DB_PASS:-pg_password}
      - POSTGRES_DB=${DB_NAME:-yummi}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-yammi}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
